### ISSUE TITLE
Recommendation && Suggestions 

### ISSUE THREAD

**Issue by Bekhzod96** [Bekhzod96/theNextWeb#2]
**Team #95 find such kind of issues:**

- It is best practice to start implementing a mobile version of the web page
- Using h6 tag as default disable none is so practical
- Background gradient in the background of the image's description is missed 
- It needs to add some margin on the logo header part of the page
_Happy Coding_

**Comment by ybadmus** [comment]
**Great work Erkin! Keep it up!**

Here are some changes to improve

- Work on the **Latest News** section when the screen size is below 768px, also add some padding to the sides.
- The whole website should have a bit of padding at the sides.
- Check HTML Validation errors. 
- Try not to use squares in the icons in the footer.
- Try to use the right arrow icon instead of the greater than character.
- Use more article and section tags instead of a lot of divs.
- Don't override flex class in css.
